### ISSUE TITLE
Zone name and type not working on a multi-alarm deployment

### ISSUE THREAD

**Issue by stezak77** [maxill1/node-red-contrib-ialarm#2]
I'm using this node red integration to control two different alarm systems connected to the same network, each one with its own ip address, port and credentials.
All zone properties are correct except for zone name and type.
Names and types of the second alarm system zones are evaluated from the first alarm system zones.
The issue should be due to zone caching implemented at global level instead at alarm instance level.

**Comment by maxill1** [comment]
You are right. I will remove the cache from global context in next release. Thank you.

**Comment by stezak77** [comment]
Thank you :)

**Comment by maxill1** [comment]
0.1.3 is out with cache on server node. I can't test it directly since I don't own two alarms. Please let me know if the fix is working.

**Comment by stezak77** [comment]
Thank you for the prompt fix. I tested it and works great now.

**Comment by stezak77** [comment]
Hi @maxill1 I think this issue can be closed
