### ISSUE TITLE
Triggered missing

### ISSUE THREAD

**Issue by wifi75** [maxill1/node-red-contrib-ialarm#6]
Hello How I can get triggered function?
I need it to turn on some lights when there is an alarm

**Comment by maxill1** [comment]
Just configure a "ialarm status" node and send a request (with a timeout or whatever you need).
In the response you will find a "zones" property with all the sensors and a "status" property with one of:

      * ARMED_AWAY
      * ARMED_HOME
      * DISARMED
      * TRIGGERED

This is the data you may find (in the example only 1 zone is returned):
```
{
    "zones": [
        {
            "id": 1,
            "status": "0",
            "lastChecked": "2021-03-29T10:17:13.180Z",
            "message": "OK",
            "ok": true,
            "alarm": false,
            "bypass": false,
            "lowbat": false,
            "fault": false,
            "open": false,
            "name": "Ingresso",
            "type": "Ritardata"
        }
    ],
    "status": "DISARMED"
}
```
